/**
 * Redmine Users Data
 * Auto-generated from Redmine API
 * Total users: 162
 * Last updated: 2025-11-20T16:00:48.052Z
 */

export interface RedmineUser {
  id: number;
  value: number;
  label: string;
  login: string;
  firstname: string;
  lastname: string;
  mail: string;
  admin: boolean;
  note: string;
  lastLoginOn: string | null;
}

export const REDMINE_USERS: RedmineUser[] = [
  {
    "id": 481,
    "value": 481,
    "label": "an.nguyen Ja (an.nguyen)",
    "login": "an.nguyen",
    "firstname": "an.nguyen",
    "lastname": "Ja",
    "mail": "an.nguyen@drjoy.vn",
    "admin": false,
    "note": "Java",
    "lastLoginOn": "2025-11-19T02:13:44Z"
  },
  {
    "id": 576,
    "value": 576,
    "label": "anh.do Ty (anh.do@drjoy.vn)",
    "login": "anh.do@drjoy.vn",
    "firstname": "anh.do",
    "lastname": "Ty",
    "mail": "anh.do@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-18T10:08:32Z"
  },
  {
    "id": 605,
    "value": 605,
    "label": "anh.hoang Te (anh.hoang@drjoy.vn)",
    "login": "anh.hoang@drjoy.vn",
    "firstname": "anh.hoang",
    "lastname": "Te",
    "mail": "anh.hoang@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T00:59:37Z"
  },
  {
    "id": 438,
    "value": 438,
    "label": "anh.le Te (anh.le@drjoy.vn)",
    "login": "anh.le@drjoy.vn",
    "firstname": "anh.le",
    "lastname": "Te",
    "mail": "anh.le@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T12:16:09Z"
  },
  {
    "id": 521,
    "value": 521,
    "label": "anh.nguyen2 Te (anh.nguyen2@drjoy.vn)",
    "login": "anh.nguyen2@drjoy.vn",
    "firstname": "anh.nguyen2",
    "lastname": "Te",
    "mail": "anh.nguyen2@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-20T00:43:54Z"
  },
  {
    "id": 599,
    "value": 599,
    "label": "chau.nguyen cs (chau.nguyen@drjoy.vn)",
    "login": "chau.nguyen@drjoy.vn",
    "firstname": "chau.nguyen",
    "lastname": "cs",
    "mail": "chau.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T03:07:12Z"
  },
  {
    "id": 553,
    "value": 553,
    "label": "chi.nguyen Te (chi.nguyen@drjoy.vn)",
    "login": "chi.nguyen@drjoy.vn",
    "firstname": "chi.nguyen",
    "lastname": "Te",
    "mail": "chi.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T06:05:58Z"
  },
  {
    "id": 501,
    "value": 501,
    "label": "chung.nguyen Ja (chung.nguyen)",
    "login": "chung.nguyen",
    "firstname": "chung.nguyen",
    "lastname": "Ja",
    "mail": "chung.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-19T01:34:07Z"
  },
  {
    "id": 571,
    "value": 571,
    "label": "cong.nguyen Ja (cong.nguyen@drjoy.vn)",
    "login": "cong.nguyen@drjoy.vn",
    "firstname": "cong.nguyen",
    "lastname": "Ja",
    "mail": "cong.nguyen@drjoy.vn",
    "admin": false,
    "note": "Java",
    "lastLoginOn": "2025-11-19T01:57:31Z"
  },
  {
    "id": 320,
    "value": 320,
    "label": "cuong.nguyen Ja (cuong.nguyen@drjoy.vn)",
    "login": "cuong.nguyen@drjoy.vn",
    "firstname": "cuong.nguyen",
    "lastname": "Ja",
    "mail": "cuong.nguyen@drjoy.vn",
    "admin": true,
    "note": "",
    "lastLoginOn": "2025-11-17T03:51:34Z"
  },
  {
    "id": 592,
    "value": 592,
    "label": "dai.duong Ty (dai.duong@drjoy.vn)",
    "login": "dai.duong@drjoy.vn",
    "firstname": "dai.duong",
    "lastname": "Ty",
    "mail": "dai.duong@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-19T01:38:16Z"
  },
  {
    "id": 537,
    "value": 537,
    "label": "dao.tran Ja (dao.tran@drjoy.vn)",
    "login": "dao.tran@drjoy.vn",
    "firstname": "dao.tran",
    "lastname": "Ja",
    "mail": "dao.tran@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-19T10:42:38Z"
  },
  {
    "id": 660,
    "value": 660,
    "label": "dat.le ai (dat.le@drjoy.vn)",
    "login": "dat.le@drjoy.vn",
    "firstname": "dat.le",
    "lastname": "ai",
    "mail": "dat.le@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-17T01:22:51Z"
  },
  {
    "id": 570,
    "value": 570,
    "label": "dat.pham Ja (dat.pham@drjoy.vn)",
    "login": "dat.pham@drjoy.vn",
    "firstname": "dat.pham",
    "lastname": "Ja",
    "mail": "dat.pham@drjoy.vn",
    "admin": false,
    "note": "Java",
    "lastLoginOn": "2025-11-20T01:01:39Z"
  },
  {
    "id": 355,
    "value": 355,
    "label": "dien.nguyen Ty (dien.nguyen@drjoy.vn)",
    "login": "dien.nguyen@drjoy.vn",
    "firstname": "dien.nguyen",
    "lastname": "Ty",
    "mail": "dien.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:03:55Z"
  },
  {
    "id": 625,
    "value": 625,
    "label": "Dinh Rina (dinh.bui@drjoy.vn)",
    "login": "dinh.bui@drjoy.vn",
    "firstname": "Dinh",
    "lastname": "Rina",
    "mail": "dinh.bui@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2024-05-13T02:24:53Z"
  },
  {
    "id": 306,
    "value": 306,
    "label": "dinh.nguyen Ja (dinh.nguyen@drjoy.vn)",
    "login": "dinh.nguyen@drjoy.vn",
    "firstname": "dinh.nguyen",
    "lastname": "Ja",
    "mail": "dinh.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T02:18:29Z"
  },
  {
    "id": 615,
    "value": 615,
    "label": "dinh.vu Ja (dinh.vu@drjoy.vn)",
    "login": "dinh.vu@drjoy.vn",
    "firstname": "dinh.vu",
    "lastname": "Ja",
    "mail": "dinh.vu@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-10-13T02:43:05Z"
  },
  {
    "id": 532,
    "value": 532,
    "label": "doai.nguyen Ty (doai.nguyen@drjoy.vn)",
    "login": "doai.nguyen@drjoy.vn",
    "firstname": "doai.nguyen",
    "lastname": "Ty",
    "mail": "doai.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:18:52Z"
  },
  {
    "id": 662,
    "value": 662,
    "label": "DrJOY 開発 (kaihatsu@drjoy.jp)",
    "login": "kaihatsu@drjoy.jp",
    "firstname": "DrJOY",
    "lastname": "開発",
    "mail": "kaihatsu@drjoy.jp",
    "admin": true,
    "note": "",
    "lastLoginOn": "2025-09-02T09:25:54Z"
  },
  {
    "id": 315,
    "value": 315,
    "label": "dung.doan Ja (dung.doan@drjoy.vn)",
    "login": "dung.doan@drjoy.vn",
    "firstname": "dung.doan",
    "lastname": "Ja",
    "mail": "dung.doan@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:48:29Z"
  },
  {
    "id": 349,
    "value": 349,
    "label": "duy.phan An (duy.phan@drjoy.vn)",
    "login": "duy.phan@drjoy.vn",
    "firstname": "duy.phan",
    "lastname": "An",
    "mail": "duy.phan@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T00:51:59Z"
  },
  {
    "id": 600,
    "value": 600,
    "label": "Hai.anhCS2 cs (anh.vu2@drjoy.vn)",
    "login": "anh.vu2@drjoy.vn",
    "firstname": "Hai.anhCS2",
    "lastname": "cs",
    "mail": "anh.vu2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T07:09:38Z"
  },
  {
    "id": 442,
    "value": 442,
    "label": "hai.nguyen3 Te (hai.nguyen3@drjoy.vn)",
    "login": "hai.nguyen3@drjoy.vn",
    "firstname": "hai.nguyen3",
    "lastname": "Te",
    "mail": "hai.nguyen3@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-17T01:24:50Z"
  },
  {
    "id": 628,
    "value": 628,
    "label": "hai.vo Ja (hai.vo@drjoy.vn)",
    "login": "hai.vo@drjoy.vn",
    "firstname": "hai.vo",
    "lastname": "Ja",
    "mail": "hai.vo@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-12T06:20:54Z"
  },
  {
    "id": 587,
    "value": 587,
    "label": "hang.hoang3 Ba (hang.hoang3@drjoy.vn)",
    "login": "hang.hoang3@drjoy.vn",
    "firstname": "hang.hoang3",
    "lastname": "Ba",
    "mail": "hang.hoang3@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:37:23Z"
  },
  {
    "id": 573,
    "value": 573,
    "label": "hang.nguyen Te (hang.nguyen@drjoy.vn)",
    "login": "hang.nguyen@drjoy.vn",
    "firstname": "hang.nguyen",
    "lastname": "Te",
    "mail": "hang.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T00:59:14Z"
  },
  {
    "id": 607,
    "value": 607,
    "label": "hang.pham Com (hang.pham@drjoy.vn)",
    "login": "hang.pham@drjoy.vn",
    "firstname": "hang.pham",
    "lastname": "Com",
    "mail": "hang.pham@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:46:14Z"
  },
  {
    "id": 572,
    "value": 572,
    "label": "hien.le Ty (hien.le@drjoy.vn)",
    "login": "hien.le@drjoy.vn",
    "firstname": "hien.le",
    "lastname": "Ty",
    "mail": "hien.le@drjoy.vn",
    "admin": false,
    "note": "Type Script",
    "lastLoginOn": "2025-11-17T01:08:58Z"
  },
  {
    "id": 627,
    "value": 627,
    "label": "hien.pham2 Te (hien.pham2@drjoy.vn)",
    "login": "hien.pham2@drjoy.vn",
    "firstname": "hien.pham2",
    "lastname": "Te",
    "mail": "hien.pham2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T03:06:54Z"
  },
  {
    "id": 644,
    "value": 644,
    "label": "hoa.nguyen Te (hoa.nguyen@drjoy.vn)",
    "login": "hoa.nguyen@drjoy.vn",
    "firstname": "hoa.nguyen",
    "lastname": "Te",
    "mail": "hoa.nguyen@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-12T09:41:36Z"
  },
  {
    "id": 580,
    "value": 580,
    "label": "hoan.duong Ja (hoan.duong@drjoy.vn)",
    "login": "hoan.duong@drjoy.vn",
    "firstname": "hoan.duong",
    "lastname": "Ja",
    "mail": "hoan.duong@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-18T03:34:54Z"
  },
  {
    "id": 564,
    "value": 564,
    "label": "hoang.le Ja (hoang.le@drjoy.vn)",
    "login": "hoang.le@drjoy.vn",
    "firstname": "hoang.le",
    "lastname": "Ja",
    "mail": "hoang.le@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:02:25Z"
  },
  {
    "id": 314,
    "value": 314,
    "label": "hong.tran Ty (hong.tran@drjoy.vn)",
    "login": "hong.tran@drjoy.vn",
    "firstname": "hong.tran",
    "lastname": "Ty",
    "mail": "hong.tran@drjoy.vn",
    "admin": false,
    "note": "Type Script",
    "lastLoginOn": "2025-11-20T01:00:21Z"
  },
  {
    "id": 451,
    "value": 451,
    "label": "hue.dang Te (hue.dang@drjoy.vn)",
    "login": "hue.dang@drjoy.vn",
    "firstname": "hue.dang",
    "lastname": "Te",
    "mail": "hue.dang@drjoy.vn",
    "admin": false,
    "note": "CS",
    "lastLoginOn": "2025-11-20T07:32:52Z"
  },
  {
    "id": 310,
    "value": 310,
    "label": "hung.dang ja (hung.dang@drjoy.vn)",
    "login": "hung.dang@drjoy.vn",
    "firstname": "hung.dang",
    "lastname": "ja",
    "mail": "hung.dang@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-14T07:12:49Z"
  },
  {
    "id": 602,
    "value": 602,
    "label": "huong.nguyen Ty (huong.nguyen@drjoy.vn)",
    "login": "huong.nguyen@drjoy.vn",
    "firstname": "huong.nguyen",
    "lastname": "Ty",
    "mail": "huong.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:50:30Z"
  },
  {
    "id": 643,
    "value": 643,
    "label": "huy.hoang Ja (huy.hoang@drjoy.vn)",
    "login": "huy.hoang@drjoy.vn",
    "firstname": "huy.hoang",
    "lastname": "Ja",
    "mail": "huy.hoang@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T03:59:38Z"
  },
  {
    "id": 546,
    "value": 546,
    "label": "lam.nguyen Ja (lam.nguyen@drjoy.vn)",
    "login": "lam.nguyen@drjoy.vn",
    "firstname": "lam.nguyen",
    "lastname": "Ja",
    "mail": "lam.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-13T09:10:55Z"
  },
  {
    "id": 517,
    "value": 517,
    "label": "lan.duong Te (lan.duong@drjoy.vn)",
    "login": "lan.duong@drjoy.vn",
    "firstname": "lan.duong",
    "lastname": "Te",
    "mail": "lan.duong@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-17T01:06:27Z"
  },
  {
    "id": 634,
    "value": 634,
    "label": "Lanh リョウコ (lanh.le@drjoy.vn)",
    "login": "lanh.le@drjoy.vn",
    "firstname": "Lanh",
    "lastname": "リョウコ",
    "mail": "lanh.le@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-18T01:09:17Z"
  },
  {
    "id": 598,
    "value": 598,
    "label": "Linh Dieu (linh.nguyen@drjoy.vn)",
    "login": "linh.nguyen@drjoy.vn",
    "firstname": "Linh",
    "lastname": "Dieu",
    "mail": "linh.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-04-14T02:47:50Z"
  },
  {
    "id": 648,
    "value": 648,
    "label": "linh.chu Co (linh.chu@drjoy.vn)",
    "login": "linh.chu@drjoy.vn",
    "firstname": "linh.chu",
    "lastname": "Co",
    "mail": "linh.chu@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-02-14T09:43:29Z"
  },
  {
    "id": 311,
    "value": 311,
    "label": "linh.tran Ty (linh.tran@drjoy.vn)",
    "login": "linh.tran@drjoy.vn",
    "firstname": "linh.tran",
    "lastname": "Ty",
    "mail": "linh.tran@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T15:14:27Z"
  },
  {
    "id": 590,
    "value": 590,
    "label": "linh.vu2 Te (linh.vu2@drjoy.vn)",
    "login": "linh.vu2@drjoy.vn",
    "firstname": "linh.vu2",
    "lastname": "Te",
    "mail": "linh.vu2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-13T15:04:24Z"
  },
  {
    "id": 512,
    "value": 512,
    "label": "loan.pham Te (loan.pham)",
    "login": "loan.pham",
    "firstname": "loan.pham",
    "lastname": "Te",
    "mail": "loan.pham@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-19T01:00:30Z"
  },
  {
    "id": 392,
    "value": 392,
    "label": "mai.le Te (mai.le@drjoy.vn)",
    "login": "mai.le@drjoy.vn",
    "firstname": "mai.le",
    "lastname": "Te",
    "mail": "mai.le@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-19T01:13:56Z"
  },
  {
    "id": 540,
    "value": 540,
    "label": "minh.nguyen Te (minh.nguyen@drjoy.vn)",
    "login": "minh.nguyen@drjoy.vn",
    "firstname": "minh.nguyen",
    "lastname": "Te",
    "mail": "minh.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-10-29T02:57:28Z"
  },
  {
    "id": 325,
    "value": 325,
    "label": "nam.nguyen An (nam.nguyen@drjoy.vn)",
    "login": "nam.nguyen@drjoy.vn",
    "firstname": "nam.nguyen",
    "lastname": "An",
    "mail": "nam.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:14:20Z"
  },
  {
    "id": 536,
    "value": 536,
    "label": "nam.phan Ja (nam.phan@drjoy.vn)",
    "login": "nam.phan@drjoy.vn",
    "firstname": "nam.phan",
    "lastname": "Ja",
    "mail": "nam.phan@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:14:21Z"
  },
  {
    "id": 319,
    "value": 319,
    "label": "nam.to Ty (nam.to@drjoy.vn)",
    "login": "nam.to@drjoy.vn",
    "firstname": "nam.to",
    "lastname": "Ty",
    "mail": "nam.to@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-10T02:38:29Z"
  },
  {
    "id": 393,
    "value": 393,
    "label": "nga.nguyen Ty (nga.nguyen@drjoy.vn)",
    "login": "nga.nguyen@drjoy.vn",
    "firstname": "nga.nguyen",
    "lastname": "Ty",
    "mail": "nga.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:00:11Z"
  },
  {
    "id": 305,
    "value": 305,
    "label": "nga.tran Te (nga.tran@drjoy.vn)",
    "login": "nga.tran@drjoy.vn",
    "firstname": "nga.tran",
    "lastname": "Te",
    "mail": "nga.tran@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:11:47Z"
  },
  {
    "id": 478,
    "value": 478,
    "label": "nhung.nguyen Te (nhung.nguyen)",
    "login": "nhung.nguyen",
    "firstname": "nhung.nguyen",
    "lastname": "Te",
    "mail": "nhung.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T09:28:54Z"
  },
  {
    "id": 637,
    "value": 637,
    "label": "nhung.nguyen3 Co (nhung.nguyen3@drjoy.vn)",
    "login": "nhung.nguyen3@drjoy.vn",
    "firstname": "nhung.nguyen3",
    "lastname": "Co",
    "mail": "nhung.nguyen3@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:18:27Z"
  },
  {
    "id": 611,
    "value": 611,
    "label": "nhung.pham Te (nhung.pham@drjoy.vn)",
    "login": "nhung.pham@drjoy.vn",
    "firstname": "nhung.pham",
    "lastname": "Te",
    "mail": "nhung.pham@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-19T02:17:35Z"
  },
  {
    "id": 560,
    "value": 560,
    "label": "oanh.leu Te (oanh.leu@drjoy.vn)",
    "login": "oanh.leu@drjoy.vn",
    "firstname": "oanh.leu",
    "lastname": "Te",
    "mail": "oanh.leu@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T02:06:52Z"
  },
  {
    "id": 411,
    "value": 411,
    "label": "pgtest@drjoy.vn Tool (pgtest@drjoy.vn)",
    "login": "pgtest@drjoy.vn",
    "firstname": "pgtest@drjoy.vn",
    "lastname": "Tool",
    "mail": "pgtest@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T04:36:45Z"
  },
  {
    "id": 378,
    "value": 378,
    "label": "phong.le Ja (phong.le@drjoy.vn)",
    "login": "phong.le@drjoy.vn",
    "firstname": "phong.le",
    "lastname": "Ja",
    "mail": "phong.le@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T10:10:04Z"
  },
  {
    "id": 659,
    "value": 659,
    "label": "phu.tran gcp (phu.tran@drjoy.vn)",
    "login": "phu.tran@drjoy.vn",
    "firstname": "phu.tran",
    "lastname": "gcp",
    "mail": "phu.tran@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T04:17:51Z"
  },
  {
    "id": 398,
    "value": 398,
    "label": "phuong.luu Te (phuong.luu@drjoy.vn)",
    "login": "phuong.luu@drjoy.vn",
    "firstname": "phuong.luu",
    "lastname": "Te",
    "mail": "phuong.luu@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T04:43:45Z"
  },
  {
    "id": 566,
    "value": 566,
    "label": "phuong.tran Te (phuong.tran@drjoy.vn)",
    "login": "phuong.tran@drjoy.vn",
    "firstname": "phuong.tran",
    "lastname": "Te",
    "mail": "phuong.tran@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:11:52Z"
  },
  {
    "id": 479,
    "value": 479,
    "label": "phuong.vu Te (phuong.vu)",
    "login": "phuong.vu",
    "firstname": "phuong.vu",
    "lastname": "Te",
    "mail": "phuong.vu@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-20T01:53:47Z"
  },
  {
    "id": 326,
    "value": 326,
    "label": "quoc.nguyen iO (quoc.nguyen@drjoy.vn)",
    "login": "quoc.nguyen@drjoy.vn",
    "firstname": "quoc.nguyen",
    "lastname": "iO",
    "mail": "quoc.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-04T01:07:21Z"
  },
  {
    "id": 656,
    "value": 656,
    "label": "Redmine MCP (redminemcp)",
    "login": "redminemcp",
    "firstname": "Redmine",
    "lastname": "MCP",
    "mail": "redminemcp@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T09:44:04Z"
  },
  {
    "id": 617,
    "value": 617,
    "label": "Shinya Aramaki (aramaki.s@dejoy.jp)",
    "login": "aramaki.s@dejoy.jp",
    "firstname": "Shinya",
    "lastname": "Aramaki",
    "mail": "aramaki.s@dejoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": null
  },
  {
    "id": 647,
    "value": 647,
    "label": "son.ha ui (son.ha@drjoy.vn)",
    "login": "son.ha@drjoy.vn",
    "firstname": "son.ha",
    "lastname": "ui",
    "mail": "son.ha@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-07-16T07:27:58Z"
  },
  {
    "id": 383,
    "value": 383,
    "label": "son.nguyen2 Ty (son.nguyen2@drjoy.vn)",
    "login": "son.nguyen2@drjoy.vn",
    "firstname": "son.nguyen2",
    "lastname": "Ty",
    "mail": "son.nguyen2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:32:46Z"
  },
  {
    "id": 631,
    "value": 631,
    "label": "son.nguyen3 Ja (son.nguyen3@drjoy.vn)",
    "login": "son.nguyen3@drjoy.vn",
    "firstname": "son.nguyen3",
    "lastname": "Ja",
    "mail": "son.nguyen3@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T09:04:25Z"
  },
  {
    "id": 520,
    "value": 520,
    "label": "tam.truong Te (tam.truong@drjoy.vn)",
    "login": "tam.truong@drjoy.vn",
    "firstname": "tam.truong",
    "lastname": "Te",
    "mail": "tam.truong@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:30:45Z"
  },
  {
    "id": 642,
    "value": 642,
    "label": "thang.nguyen Ba (thang.nguyen@drjoy.vn)",
    "login": "thang.nguyen@drjoy.vn",
    "firstname": "thang.nguyen",
    "lastname": "Ba",
    "mail": "thang.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-10T19:31:54Z"
  },
  {
    "id": 658,
    "value": 658,
    "label": "thanh.bui2 iO (thanh.bui2@drjoy.vn)",
    "login": "thanh.bui2@drjoy.vn",
    "firstname": "thanh.bui2",
    "lastname": "iO",
    "mail": "thanh.bui2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T09:51:54Z"
  },
  {
    "id": 632,
    "value": 632,
    "label": "thanh.nguyen2 Ja (thanh.nguyen2@drjoy.vn)",
    "login": "thanh.nguyen2@drjoy.vn",
    "firstname": "thanh.nguyen2",
    "lastname": "Ja",
    "mail": "thanh.nguyen2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T06:35:18Z"
  },
  {
    "id": 488,
    "value": 488,
    "label": "thanh.tran Ja (thanh.tran)",
    "login": "thanh.tran",
    "firstname": "thanh.tran",
    "lastname": "Ja",
    "mail": "thanh.tran@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-18T07:48:39Z"
  },
  {
    "id": 666,
    "value": 666,
    "label": "thao.do BA (thao.do@drjoy.vn)",
    "login": "thao.do@drjoy.vn",
    "firstname": "thao.do",
    "lastname": "BA",
    "mail": "thao.do@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T15:42:58Z"
  },
  {
    "id": 370,
    "value": 370,
    "label": "thao.leu Te (thao.leu@drjoy.vn)",
    "login": "thao.leu@drjoy.vn",
    "firstname": "thao.leu",
    "lastname": "Te",
    "mail": "thao.leu@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-17T00:59:20Z"
  },
  {
    "id": 402,
    "value": 402,
    "label": "thao.nguyen Te (thao.nguyen@drjoy.vn)",
    "login": "thao.nguyen@drjoy.vn",
    "firstname": "thao.nguyen",
    "lastname": "Te",
    "mail": "thao.nguyen@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-20T01:11:05Z"
  },
  {
    "id": 409,
    "value": 409,
    "label": "thoa.le Te (thoa.le@drjoy.vn)",
    "login": "thoa.le@drjoy.vn",
    "firstname": "thoa.le",
    "lastname": "Te",
    "mail": "thoa.le@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:01:26Z"
  },
  {
    "id": 498,
    "value": 498,
    "label": "thom.nguyen3 Te (thom.nguyen3@drjoy.vn)",
    "login": "thom.nguyen3@drjoy.vn",
    "firstname": "thom.nguyen3",
    "lastname": "Te",
    "mail": "thom.nguyen3@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-19T01:20:32Z"
  },
  {
    "id": 649,
    "value": 649,
    "label": "thu.dang Ty (thu.dang@drjoy.vn)",
    "login": "thu.dang@drjoy.vn",
    "firstname": "thu.dang",
    "lastname": "Ty",
    "mail": "thu.dang@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-09-27T13:19:52Z"
  },
  {
    "id": 329,
    "value": 329,
    "label": "thu.nguyen Te (thu.nguyen@drjoy.vn)",
    "login": "thu.nguyen@drjoy.vn",
    "firstname": "thu.nguyen",
    "lastname": "Te",
    "mail": "thu.nguyen@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-11T03:54:22Z"
  },
  {
    "id": 597,
    "value": 597,
    "label": "thu.nguyen2  Te (thu.nguyen2@drjoy.vn)",
    "login": "thu.nguyen2@drjoy.vn",
    "firstname": "thu.nguyen2 ",
    "lastname": "Te",
    "mail": "thu.nguyen2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T04:13:14Z"
  },
  {
    "id": 584,
    "value": 584,
    "label": "thuan.nguyen Ja (thuan.nguyen@drjoy.vn)",
    "login": "thuan.nguyen@drjoy.vn",
    "firstname": "thuan.nguyen",
    "lastname": "Ja",
    "mail": "thuan.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T13:34:01Z"
  },
  {
    "id": 653,
    "value": 653,
    "label": "thuy.le Co (thuy.le@drjoy.vn)",
    "login": "thuy.le@drjoy.vn",
    "firstname": "thuy.le",
    "lastname": "Co",
    "mail": "thuy.le@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T00:49:04Z"
  },
  {
    "id": 382,
    "value": 382,
    "label": "tien.luu Ja (tien.luu@drjoy.vn)",
    "login": "tien.luu@drjoy.vn",
    "firstname": "tien.luu",
    "lastname": "Ja",
    "mail": "tien.luu@drjoy.vn",
    "admin": false,
    "note": "Java",
    "lastLoginOn": "2025-11-19T07:10:09Z"
  },
  {
    "id": 511,
    "value": 511,
    "label": "tinh.tran Ja (tinh.tran)",
    "login": "tinh.tran",
    "firstname": "tinh.tran",
    "lastname": "Ja",
    "mail": "tinh.tran@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-18T03:50:12Z"
  },
  {
    "id": 559,
    "value": 559,
    "label": "tra.pham Ja (tra.pham@drjoy.vn)",
    "login": "tra.pham@drjoy.vn",
    "firstname": "tra.pham",
    "lastname": "Ja",
    "mail": "tra.pham@drjoy.vn",
    "admin": false,
    "note": "Java",
    "lastLoginOn": "2025-11-20T13:44:21Z"
  },
  {
    "id": 581,
    "value": 581,
    "label": "tra.pham2 Te (tra.pham2@drjoy.vn)",
    "login": "tra.pham2@drjoy.vn",
    "firstname": "tra.pham2",
    "lastname": "Te",
    "mail": "tra.pham2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-19T01:14:19Z"
  },
  {
    "id": 458,
    "value": 458,
    "label": "trang.le2  Te (trang.le2@drjoy.vn)",
    "login": "trang.le2@drjoy.vn",
    "firstname": "trang.le2 ",
    "lastname": "Te",
    "mail": "trang.le2@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-20T00:51:32Z"
  },
  {
    "id": 562,
    "value": 562,
    "label": "trang.nguyen3 Te (trang.nguyen3@drjoy.vn)",
    "login": "trang.nguyen3@drjoy.vn",
    "firstname": "trang.nguyen3",
    "lastname": "Te",
    "mail": "trang.nguyen3@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:14:48Z"
  },
  {
    "id": 390,
    "value": 390,
    "label": "tu.do Ja (tu.do@drjoy.vn)",
    "login": "tu.do@drjoy.vn",
    "firstname": "tu.do",
    "lastname": "Ja",
    "mail": "tu.do@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T06:31:02Z"
  },
  {
    "id": 604,
    "value": 604,
    "label": "tuan.le2 iO (tuan.le2@drjoy.vn)",
    "login": "tuan.le2@drjoy.vn",
    "firstname": "tuan.le2",
    "lastname": "iO",
    "mail": "tuan.le2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-18T07:41:48Z"
  },
  {
    "id": 446,
    "value": 446,
    "label": "tuan.nguyen2 An (tuan.nguyen2@drjoy.vn)",
    "login": "tuan.nguyen2@drjoy.vn",
    "firstname": "tuan.nguyen2",
    "lastname": "An",
    "mail": "tuan.nguyen2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:37:21Z"
  },
  {
    "id": 661,
    "value": 661,
    "label": "tuan.vu co (tuan.vu@drjoy.vn)",
    "login": "tuan.vu@drjoy.vn",
    "firstname": "tuan.vu",
    "lastname": "co",
    "mail": "tuan.vu@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T02:18:16Z"
  },
  {
    "id": 313,
    "value": 313,
    "label": "tung.le Ja (tung.le@drjoy.vn)",
    "login": "tung.le@drjoy.vn",
    "firstname": "tung.le",
    "lastname": "Ja",
    "mail": "tung.le@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T06:30:33Z"
  },
  {
    "id": 565,
    "value": 565,
    "label": "tuyen.tran Ja (tuyen.tran@drjoy.vn)",
    "login": "tuyen.tran@drjoy.vn",
    "firstname": "tuyen.tran",
    "lastname": "Ja",
    "mail": "tuyen.tran@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-19T01:57:02Z"
  },
  {
    "id": 524,
    "value": 524,
    "label": "vi.do Ty (vi.do@drjoy.vn)",
    "login": "vi.do@drjoy.vn",
    "firstname": "vi.do",
    "lastname": "Ty",
    "mail": "vi.do@drjoy.vn",
    "admin": false,
    "note": "HTML/CSS",
    "lastLoginOn": "2025-11-17T03:23:13Z"
  },
  {
    "id": 655,
    "value": 655,
    "label": "vi.nguyen ヴィ (vi.nguyen@drjoy.vn)",
    "login": "vi.nguyen@drjoy.vn",
    "firstname": "vi.nguyen",
    "lastname": "ヴィ",
    "mail": "vi.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T02:20:41Z"
  },
  {
    "id": 441,
    "value": 441,
    "label": "vuD.dinh iO (vu.dinh@drjoy.vn)",
    "login": "vu.dinh@drjoy.vn",
    "firstname": "vuD.dinh",
    "lastname": "iO",
    "mail": "vu.dinh@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:11:28Z"
  },
  {
    "id": 542,
    "value": 542,
    "label": "xuyen.nguyen Te (xuyen.nguyen@drjoy.vn)",
    "login": "xuyen.nguyen@drjoy.vn",
    "firstname": "xuyen.nguyen",
    "lastname": "Te",
    "mail": "xuyen.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:30:32Z"
  },
  {
    "id": 353,
    "value": 353,
    "label": "yen.phan Te (yen.phan@drjoy.vn)",
    "login": "yen.phan@drjoy.vn",
    "firstname": "yen.phan",
    "lastname": "Te",
    "mail": "yen.phan@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-20T01:01:14Z"
  },
  {
    "id": 569,
    "value": 569,
    "label": "アカウント 参照用共有 (sharedRedmineId)",
    "login": "sharedRedmineId",
    "firstname": "アカウント",
    "lastname": "参照用共有",
    "mail": "katagiri.h*2@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T10:01:10Z"
  },
  {
    "id": 654,
    "value": 654,
    "label": "アキナリ thanh.bui Com (thanh.bui@drjoy.vn)",
    "login": "thanh.bui@drjoy.vn",
    "firstname": "アキナリ",
    "lastname": "thanh.bui Com",
    "mail": "thanh.bui@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-06-23T01:19:36Z"
  },
  {
    "id": 302,
    "value": 302,
    "label": "イエン yen.nguyen (yen.nguyen@drjoy.vn)",
    "login": "yen.nguyen@drjoy.vn",
    "firstname": "イエン",
    "lastname": "yen.nguyen",
    "mail": "yen.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-13T13:40:58Z"
  },
  {
    "id": 406,
    "value": 406,
    "label": "カット cat.nguyen (cat.nguyen@drjoy.vn)",
    "login": "cat.nguyen@drjoy.vn",
    "firstname": "カット",
    "lastname": "cat.nguyen",
    "mail": "cat.nguyen@drjoy.vn",
    "admin": true,
    "note": "",
    "lastLoginOn": "2025-11-20T03:34:09Z"
  },
  {
    "id": 594,
    "value": 594,
    "label": "ゲン huyen.nguyen2 SS (huyen.nguyen2@drjoy.vn)",
    "login": "huyen.nguyen2@drjoy.vn",
    "firstname": "ゲン",
    "lastname": "huyen.nguyen2 SS",
    "mail": "huyen.nguyen2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T10:02:32Z"
  },
  {
    "id": 595,
    "value": 595,
    "label": "コウ phuong.le SS (phuong.le@drjoy.vn)",
    "login": "phuong.le@drjoy.vn",
    "firstname": "コウ",
    "lastname": "phuong.le SS",
    "mail": "phuong.le@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2023-12-12T07:05:43Z"
  },
  {
    "id": 312,
    "value": 312,
    "label": "ゴク son.nguyen (son.nguyen@drjoy.vn)",
    "login": "son.nguyen@drjoy.vn",
    "firstname": "ゴク",
    "lastname": "son.nguyen",
    "mail": "son.nguyen@drjoy.vn",
    "admin": false,
    "note": "Android",
    "lastLoginOn": "2025-11-20T01:28:28Z"
  },
  {
    "id": 601,
    "value": 601,
    "label": "ジャム Tam (tam.do2@drjoy.vn)",
    "login": "tam.do2@drjoy.vn",
    "firstname": "ジャム",
    "lastname": "Tam",
    "mail": "tam.do2@drjoy.vn",
    "admin": false,
    "note": "CS",
    "lastLoginOn": "2024-06-20T04:08:54Z"
  },
  {
    "id": 399,
    "value": 399,
    "label": "ジュン chinh.vu (chinh.vu@drjoy.vn)",
    "login": "chinh.vu@drjoy.vn",
    "firstname": "ジュン",
    "lastname": "chinh.vu",
    "mail": "chinh.vu@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:19:54Z"
  },
  {
    "id": 327,
    "value": 327,
    "label": "タイン thanh.vu (thanh.vu@drjoy.vn)",
    "login": "thanh.vu@drjoy.vn",
    "firstname": "タイン",
    "lastname": "thanh.vu",
    "mail": "thanh.vu@drjoy.vn",
    "admin": true,
    "note": "",
    "lastLoginOn": "2025-11-20T01:23:09Z"
  },
  {
    "id": 462,
    "value": 462,
    "label": "タツ tuan.le (tuan.le@drjoy.vn)",
    "login": "tuan.le@drjoy.vn",
    "firstname": "タツ",
    "lastname": "tuan.le",
    "mail": "tuan.le@drjoy.vn",
    "admin": true,
    "note": "",
    "lastLoginOn": "2025-11-20T01:36:41Z"
  },
  {
    "id": 463,
    "value": 463,
    "label": "チ ngoc.le (ngoc.le@drjoy.vn)",
    "login": "ngoc.le@drjoy.vn",
    "firstname": "チ",
    "lastname": "ngoc.le",
    "mail": "ngoc.le@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T02:17:28Z"
  },
  {
    "id": 523,
    "value": 523,
    "label": "チー chi.hoang CS (chi.hoang@drjoy.vn)",
    "login": "chi.hoang@drjoy.vn",
    "firstname": "チー",
    "lastname": "chi.hoang CS",
    "mail": "chi.hoang@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T07:36:56Z"
  },
  {
    "id": 345,
    "value": 345,
    "label": "チャン trang.hoang (trang.hoang@drjoy.vn)",
    "login": "trang.hoang@drjoy.vn",
    "firstname": "チャン",
    "lastname": "trang.hoang",
    "mail": "trang.hoang@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-19T06:15:59Z"
  },
  {
    "id": 549,
    "value": 549,
    "label": "チャンチャン trang.tran CS (trang.tran@drjoy.vn)",
    "login": "trang.tran@drjoy.vn",
    "firstname": "チャンチャン",
    "lastname": "trang.tran CS",
    "mail": "trang.tran@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": null
  },
  {
    "id": 621,
    "value": 621,
    "label": "チョウ Zhang (zhang.y@drjoy.jp)",
    "login": "zhang.y@drjoy.jp",
    "firstname": "チョウ",
    "lastname": "Zhang",
    "mail": "zhang.y@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": null
  },
  {
    "id": 522,
    "value": 522,
    "label": "トシ Tuan (tuan.nguyen4@drjoy.vn)",
    "login": "tuan.nguyen4@drjoy.vn",
    "firstname": "トシ",
    "lastname": "Tuan",
    "mail": "tuan.nguyen4@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-12T07:59:56Z"
  },
  {
    "id": 567,
    "value": 567,
    "label": "ハイ hai.nguyen4 (hai.nguyen4@drjoy.vn)",
    "login": "hai.nguyen4@drjoy.vn",
    "firstname": "ハイ",
    "lastname": "hai.nguyen4",
    "mail": "hai.nguyen4@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-17T09:15:17Z"
  },
  {
    "id": 354,
    "value": 354,
    "label": "ハオ hao.dam (hao.dam@drjoy.vn)",
    "login": "hao.dam@drjoy.vn",
    "firstname": "ハオ",
    "lastname": "hao.dam",
    "mail": "hao.dam@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T06:02:51Z"
  },
  {
    "id": 568,
    "value": 568,
    "label": "ハル thanh.pham Co (thanh.pham@drjoy.vn)",
    "login": "thanh.pham@drjoy.vn",
    "firstname": "ハル",
    "lastname": "thanh.pham Co",
    "mail": "thanh.pham@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:22:40Z"
  },
  {
    "id": 664,
    "value": 664,
    "label": "ハルカ Phuong (phuong.vu2@drjoy.vn)",
    "login": "phuong.vu2@drjoy.vn",
    "firstname": "ハルカ",
    "lastname": "Phuong",
    "mail": "phuong.vu2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-13T01:45:29Z"
  },
  {
    "id": 424,
    "value": 424,
    "label": "ビック bich.hua Co (bich.hua@drjoy.vn)",
    "login": "bich.hua@drjoy.vn",
    "firstname": "ビック",
    "lastname": "bich.hua Co",
    "mail": "bich.hua@drjoy.vn",
    "admin": false,
    "note": "CS",
    "lastLoginOn": "2025-11-20T02:23:17Z"
  },
  {
    "id": 583,
    "value": 583,
    "label": "ヒロ hoang.nguyen (hoang.nguyen@drjoy.vn)",
    "login": "hoang.nguyen@drjoy.vn",
    "firstname": "ヒロ",
    "lastname": "hoang.nguyen",
    "mail": "hoang.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:08:33Z"
  },
  {
    "id": 650,
    "value": 650,
    "label": "ファムフエン huyen.pham (huyen.pham@drjoy.vn)",
    "login": "huyen.pham@drjoy.vn",
    "firstname": "ファムフエン",
    "lastname": "huyen.pham",
    "mail": "huyen.pham@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T04:11:51Z"
  },
  {
    "id": 486,
    "value": 486,
    "label": "フェン huyen.nguyen te (huyen.nguyen)",
    "login": "huyen.nguyen",
    "firstname": "フェン",
    "lastname": "huyen.nguyen te",
    "mail": "huyen.nguyen@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T00:46:42Z"
  },
  {
    "id": 495,
    "value": 495,
    "label": "フオンマイ mai.le2 SS (mai.le2@drjoy.vn)",
    "login": "mai.le2@drjoy.vn",
    "firstname": "フオンマイ",
    "lastname": "mai.le2 SS",
    "mail": "mai.le2@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-18T01:50:37Z"
  },
  {
    "id": 475,
    "value": 475,
    "label": "ホア hoa.dao AC (hoa.dao@drjoy.vn)",
    "login": "hoa.dao@drjoy.vn",
    "firstname": "ホア",
    "lastname": "hoa.dao AC",
    "mail": "hoa.dao@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T02:28:23Z"
  },
  {
    "id": 557,
    "value": 557,
    "label": "ホンリン linh.vu Com (linh.vu@drjoy.vn)",
    "login": "linh.vu@drjoy.vn",
    "firstname": "ホンリン",
    "lastname": "linh.vu Com",
    "mail": "linh.vu@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T06:28:36Z"
  },
  {
    "id": 645,
    "value": 645,
    "label": "ミー my.tran Co (my.tran@drjoy.vn)",
    "login": "my.tran@drjoy.vn",
    "firstname": "ミー my.tran",
    "lastname": "Co",
    "mail": "my.tran@drjoy.vn",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-11T02:19:55Z"
  },
  {
    "id": 657,
    "value": 657,
    "label": "リュウ シュウモン (ryu.s@drjoy.jp)",
    "login": "ryu.s@drjoy.jp",
    "firstname": "リュウ",
    "lastname": "シュウモン",
    "mail": "ryu.s@drjoy.jp",
    "admin": false,
    "note": "Designer",
    "lastLoginOn": "2025-11-20T07:42:40Z"
  },
  {
    "id": 552,
    "value": 552,
    "label": "リリース ticket (release)",
    "login": "release",
    "firstname": "リリース",
    "lastname": "ticket",
    "mail": "katagiri.h+1@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": null
  },
  {
    "id": 400,
    "value": 400,
    "label": "ルエン luyen.nguyen Co (luyen.nguyen@drjoy.vn)",
    "login": "luyen.nguyen@drjoy.vn",
    "firstname": "ルエン",
    "lastname": "luyen.nguyen Co",
    "mail": "luyen.nguyen@drjoy.vn",
    "admin": false,
    "note": "Tester",
    "lastLoginOn": "2025-11-20T04:01:57Z"
  },
  {
    "id": 170,
    "value": 170,
    "label": "三田 mita (mita.f@drjoy.jp)",
    "login": "mita.f@drjoy.jp",
    "firstname": "三田",
    "lastname": "mita",
    "mail": "mita.f@drjoy.jp",
    "admin": false,
    "note": "CS",
    "lastLoginOn": "2025-11-20T04:53:27Z"
  },
  {
    "id": 663,
    "value": 663,
    "label": "井上 inoue (inoue.t@drjoy.jp)",
    "login": "inoue.t@drjoy.jp",
    "firstname": "井上",
    "lastname": "inoue",
    "mail": "inoue.t@drjoy.jp",
    "admin": false,
    "note": "CS",
    "lastLoginOn": "2025-11-14T08:50:28Z"
  },
  {
    "id": 652,
    "value": 652,
    "label": "伊藤 Hikari (ito.h@drjoy.jp)",
    "login": "ito.h@drjoy.jp",
    "firstname": "伊藤",
    "lastname": "Hikari",
    "mail": "ito.h@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T08:50:36Z"
  },
  {
    "id": 12,
    "value": 12,
    "label": "佐々木 Sasaki (sasaki.f@drjoy.jp)",
    "login": "sasaki.f@drjoy.jp",
    "firstname": "佐々木",
    "lastname": "Sasaki",
    "mail": "sasaki.f@drjoy.jp",
    "admin": true,
    "note": "JP Engineer",
    "lastLoginOn": "2025-11-20T01:03:24Z"
  },
  {
    "id": 608,
    "value": 608,
    "label": "前山 maeyama (maeyama.c@drjoy.jp)",
    "login": "maeyama.c@drjoy.jp",
    "firstname": "前山",
    "lastname": "maeyama",
    "mail": "maeyama.c@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-18T01:03:53Z"
  },
  {
    "id": 5,
    "value": 5,
    "label": "前田 Maeda (go-maeda)",
    "login": "go-maeda",
    "firstname": "前田",
    "lastname": "Maeda",
    "mail": "maeda.g@drjoy.jp",
    "admin": true,
    "note": "JP Engineer",
    "lastLoginOn": "2025-11-10T05:24:32Z"
  },
  {
    "id": 610,
    "value": 610,
    "label": "古田 Furuta  (furuta.w@drjoy.jp)",
    "login": "furuta.w@drjoy.jp",
    "firstname": "古田",
    "lastname": "Furuta ",
    "mail": "furuta.w@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T01:37:34Z"
  },
  {
    "id": 483,
    "value": 483,
    "label": "宗 so (so.m@drjoy.jp)",
    "login": "so.m@drjoy.jp",
    "firstname": "宗",
    "lastname": "so",
    "mail": "so.m@drjoy.jp",
    "admin": false,
    "note": "QA",
    "lastLoginOn": "2025-11-20T05:18:59Z"
  },
  {
    "id": 174,
    "value": 174,
    "label": "寺島 Terashima (terashima.m@drjoy.jp)",
    "login": "terashima.m@drjoy.jp",
    "firstname": "寺島",
    "lastname": "Terashima",
    "mail": "terashima.m@drjoy.jp",
    "admin": false,
    "note": "CS",
    "lastLoginOn": "2025-06-17T05:02:21Z"
  },
  {
    "id": 188,
    "value": 188,
    "label": "小田川 Odagawa (odagawa.s@drjoy.jp)",
    "login": "odagawa.s@drjoy.jp",
    "firstname": "小田川",
    "lastname": "Odagawa",
    "mail": "odagawa.s@drjoy.jp",
    "admin": false,
    "note": "CS",
    "lastLoginOn": "2025-11-20T02:37:24Z"
  },
  {
    "id": 646,
    "value": 646,
    "label": "小見山 komiyama (komiyama.d@drjoy.jp)",
    "login": "komiyama.d@drjoy.jp",
    "firstname": "小見山",
    "lastname": "komiyama",
    "mail": "komiyama.d@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-17T08:46:38Z"
  },
  {
    "id": 437,
    "value": 437,
    "label": "尾上 Onoe (onoe.r@drjoy.jp)",
    "login": "onoe.r@drjoy.jp",
    "firstname": "尾上",
    "lastname": "Onoe",
    "mail": "onoe.r@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-06T02:06:31Z"
  },
  {
    "id": 591,
    "value": 591,
    "label": "岡本 okamoto (okamoto.y@drjoy.jp)",
    "login": "okamoto.y@drjoy.jp",
    "firstname": "岡本",
    "lastname": "okamoto",
    "mail": "okamoto.y@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T00:37:38Z"
  },
  {
    "id": 586,
    "value": 586,
    "label": "斉藤 saito (saito.y@drjoy.jp)",
    "login": "saito.y@drjoy.jp",
    "firstname": "斉藤",
    "lastname": "saito",
    "mail": "saito.y@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-04T08:54:46Z"
  },
  {
    "id": 665,
    "value": 665,
    "label": "明李 鬼塚 (onitsuka.a@drjoy.jp)",
    "login": "onitsuka.a@drjoy.jp",
    "firstname": "明李",
    "lastname": "鬼塚",
    "mail": "onitsuka.a@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-13T03:51:26Z"
  },
  {
    "id": 622,
    "value": 622,
    "label": "本間 Honma (honma.s@drjoy.jp)",
    "login": "honma.s@drjoy.jp",
    "firstname": "本間",
    "lastname": "Honma",
    "mail": "honma.s@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": null
  },
  {
    "id": 173,
    "value": 173,
    "label": "杉本 sugimoto (sugimoto.n@drjoy.jp)",
    "login": "sugimoto.n@drjoy.jp",
    "firstname": "杉本",
    "lastname": "sugimoto",
    "mail": "sugimoto.n@drjoy.jp",
    "admin": false,
    "note": "CS",
    "lastLoginOn": "2025-11-20T00:44:22Z"
  },
  {
    "id": 257,
    "value": 257,
    "label": "片桐 katagiri (katagiri.h@drjoy.jp)",
    "login": "katagiri.h@drjoy.jp",
    "firstname": "片桐",
    "lastname": "katagiri",
    "mail": "katagiri.h@drjoy.jp",
    "admin": true,
    "note": "JP Engineer",
    "lastLoginOn": "2025-11-20T01:57:50Z"
  },
  {
    "id": 616,
    "value": 616,
    "label": "牧野 Makino (Makino.t@drjoy.jp)",
    "login": "Makino.t@drjoy.jp",
    "firstname": "牧野",
    "lastname": "Makino",
    "mail": "makino.t@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2024-04-22T08:47:59Z"
  },
  {
    "id": 527,
    "value": 527,
    "label": "相川 aikawa (aikawa.f@drjoy.jp)",
    "login": "aikawa.f@drjoy.jp",
    "firstname": "相川",
    "lastname": "aikawa",
    "mail": "aikawa.f@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-20T03:49:01Z"
  },
  {
    "id": 102,
    "value": 102,
    "label": "石松 ishimatsu (ishimatsu.h)",
    "login": "ishimatsu.h",
    "firstname": "石松",
    "lastname": "ishimatsu",
    "mail": "ishimatsu.h@drjoy.jp",
    "admin": true,
    "note": "CEO",
    "lastLoginOn": "2025-11-07T09:04:19Z"
  },
  {
    "id": 417,
    "value": 417,
    "label": "神田 kanda (kanda.y@drjoy.jp)",
    "login": "kanda.y@drjoy.jp",
    "firstname": "神田",
    "lastname": "kanda",
    "mail": "kanda.y@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-05T11:40:47Z"
  },
  {
    "id": 485,
    "value": 485,
    "label": "筒井 tsutsui (tsutsui.y@drjoy.jp)",
    "login": "tsutsui.y@drjoy.jp",
    "firstname": "筒井",
    "lastname": "tsutsui",
    "mail": "tsutsui.y@drjoy.jp",
    "admin": false,
    "note": "QA",
    "lastLoginOn": "2025-11-20T08:05:01Z"
  },
  {
    "id": 86,
    "value": 86,
    "label": "菊池 kikuchi (kikuchi.s@drjoy.jp)",
    "login": "kikuchi.s@drjoy.jp",
    "firstname": "菊池",
    "lastname": "kikuchi",
    "mail": "kikuchi.s@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-10-21T11:25:10Z"
  },
  {
    "id": 620,
    "value": 620,
    "label": "藤田 Fujita (fujita.m@drjoy.jp)",
    "login": "fujita.m@drjoy.jp",
    "firstname": "藤田",
    "lastname": "Fujita",
    "mail": "fujita.m@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-11-17T23:43:30Z"
  },
  {
    "id": 614,
    "value": 614,
    "label": "西 nishi (nishi.m@drjoy.jp)",
    "login": "nishi.m@drjoy.jp",
    "firstname": "西",
    "lastname": "nishi",
    "mail": "nishi.m@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2024-12-13T05:35:48Z"
  },
  {
    "id": 14,
    "value": 14,
    "label": "角 Sumi (sumi.k@drjoy.jp)",
    "login": "sumi.k@drjoy.jp",
    "firstname": "角",
    "lastname": "Sumi",
    "mail": "sumi.k@drjoy.jp",
    "admin": false,
    "note": "JP Engineer",
    "lastLoginOn": "2025-11-20T02:58:47Z"
  },
  {
    "id": 624,
    "value": 624,
    "label": "酒井 Sakai (sakai.m@drjoy.jp)",
    "login": "sakai.m@drjoy.jp",
    "firstname": "酒井",
    "lastname": "Sakai",
    "mail": "sakai.m@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": "2025-10-27T04:37:59Z"
  },
  {
    "id": 618,
    "value": 618,
    "label": "鈴木 Suzuki (suzuki.m@drjoy.jp)",
    "login": "suzuki.m@drjoy.jp",
    "firstname": "鈴木",
    "lastname": "Suzuki",
    "mail": "suzuki.m@drjoy.jp",
    "admin": false,
    "note": "",
    "lastLoginOn": null
  }
];

/**
 * Get user by ID
 */
export const getUserById = (id: number): RedmineUser | undefined => {
  return REDMINE_USERS.find(user => user.id === id);
};

/**
 * Get user by login
 */
export const getUserByLogin = (login: string): RedmineUser | undefined => {
  return REDMINE_USERS.find(user => user.login === login);
};

/**
 * Get all active users (users who have logged in before)
 */
export const getActiveUsers = (): RedmineUser[] => {
  return REDMINE_USERS.filter(user => user.lastLoginOn !== null);
};

/**
 * Get users for select options (id and label)
 */
export const getUserOptions = () => {
  return REDMINE_USERS.map(user => ({
    value: user.id,
    label: user.label
  }));
};

/**
 * Get active users for select options
 */
export const getActiveUserOptions = () => {
  return getActiveUsers().map(user => ({
    value: user.id,
    label: user.label
  }));
};
